name: .NET

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: 'Release'
  BUILD_VERSION: '5.x'
  BUILD_FRAMEWORK: 'net5.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.BUILD_VERSION }}

      - name: Restore .NET and Token
        run: |
          dotnet restore
          touch LebakasBot/token.txt
          echo "${{ secrets.BOT_TOKEN }}" >> LebakasBot/token.txt
    
      - name: Build .NET
        run: |
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'

      - name: Copy new Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "LebakasBot/bin/${{ env.BUILD_CONFIGURATION }}/${{ env.BUILD_FRAMEWORK }}/*"
          target: "~/lebakasbot/bin_new"
          strip_components: 4
      
      - name: Stop current Bot, exchange Files and start new Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: | 
            systemctl stop LebakasBot
            rm -r lebakasbot/bin/
            mv lebakasbot/bin_new/ lebakasbot/bin/
            mkdir lebakasbot/bin_new
            systemctl restart LebakasBot
